#
# Questo e' solo un esempio in formato OpenAPI 3.0.1 delle implementazioni API REST che metterà a disposizione ISIDATA 
#
openapi: 3.0.1
info:
  title: API ISIUniv23
  description: ISIDATA - API Tracciati record
  version: '0.1'
components:  
  securitySchemes:
    testAutenticazione:
        type: http
        scheme: basic
security:  
    - testAutenticazione: []
servers:
   - url: https://servizi1.isidata.net
paths:
  /ISIUniv23/api/SituazioneStudente:
    get:
      description: Situazione studente codice fiscale in tempo reale inclusa di esami sostenuti
      parameters:
        - name: CUStudente
          in: query
          schema:
            type: string
          required: true
          description: codice univoco studente
        - name: CUAteneo
          in: query
          schema:
            type: string
          required: true
          description: Codice univoco ateneo
      responses:
        '200':
          description: Lo studente è stato trovato e le informazioni sono state recuperate con successo
          content:
            application/json:
              schema:
                type: object
        '400':
          description: I paramentri CUStudente e CUAteneo sono obbligatori
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide