#
# Formato OpenAPI 3.0.1 delle implementazioni API REST che mette a disposizione ISIDATA 
#
openapi: 3.0.1
info:
  title: API ISIUniv23
  description: ISIDATA - API Tracciati record
  version: '0.1'
components:  
  securitySchemes:
    testAutenticazione:
        type: http
        scheme: basic
security:  
    - testAutenticazione: []
servers:
   - url: https://servizi1.isidata.net
paths:
  /ISIUniv23/api/Conteggio_Iscritti_Corso_PerAnno:
    get:
      operationId: Conteggio_Iscritti_Corso_PerAnno
      summary: Numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
      description: Numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito formato json il numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Conteggio_Iscritti_Corsi:
    get:
      operationId: Conteggio_Iscritti_Corsi
      summary: Numero di studenti iscritti ai Corsi di Studio
      description: Numero di studenti iscritti ai Corsi di Studio
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito formato json il numero di studenti iscritti ai Corsi di Studio
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Conteggio_Studenti_Votazione_MaggioreDi:
    get:
      operationId: Conteggio_Studenti_Votazione_MaggioreDi
      summary: Numero di studenti che hanno conseguito il titolo con votazione maggiore di X (parametro Voto)
      description: Numero di studenti che hanno conseguito il titolo con votazione maggiore di X (parametro Voto)
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: Voto
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito formato json il numero di studenti iscritti ai Corsi di Studio
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
