#
# Formato OpenAPI 3.0.1 delle implementazioni API REST che mette a disposizione ISIDATA. L'autenticazione sarà basata su token, ma per adesso essendo visibili dati fittizi, è sufficiente passare nell'header la chiave Authorization col valore basic test:test
#
openapi: 3.0.1
info:
  title: API ISIDATA ISIUniv23
  x-summary: API ISIDATA ISIUniv23
  version: 1.0.0
  description: ISIDATA - API Tracciati record
  termsOfService: https://example.com/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: API Support
    email: fabiofonzo@isidataservizi.it
  x-api-id: 38282e04-1f49-4c13-b131-cc25d7a6c9bf
components:  
  securitySchemes:
    testAutenticazione:
        type: http
        scheme: Basic
security:  
    - testAutenticazione: []
servers:
   - url: https://servizi1.isidata.net/ISIUniv23/api/v1
     description: Production server
tags:
  - name: status
  - name: iscritticorsixanno
  - name: iscritticorsi
  - name: studentivotazionemaggioredi
  - name: corsierogati
  - name: studentedettaglioiscrizione
  - name: studenteelencotitoli
  - name: studenticontitolo
  - name: studentiiscritti
  - name: provadiploma
paths:
  /status:
    get:
      summary: Get the API status
      operationId: status
      description: Get the API status for health check purpose
      tags:
        - status
      responses:
        '204':
          description: the server has successfully fulfilled the request and that there is no content to send.
        '500':
          description: service not running.
  /iscritticorsixanno:
    get:
      tags:
        - iscritticorsixanno
      operationId: iscritticorsixanno
      summary: Numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
      description: Numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito il numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /iscritticorsi:
    get:
      tags:
        - iscritticorsi
      operationId: iscritticorsi
      summary: Numero di studenti iscritti ai Corsi di Studio
      description: Numero di studenti iscritti ai Corsi di Studio
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito il numero di studenti iscritti ai Corsi di Studio
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /studentivotazionemaggioredi:
    get:
      tags:
        - studentivotazionemaggioredi
      operationId: studentivotazionemaggioredi
      summary: Numero di studenti che hanno conseguito il titolo con votazione maggiore di X (parametro Voto)
      description: Numero di studenti che hanno conseguito il titolo con votazione maggiore di X (parametro Voto)
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: Voto
          in: query
          schema:
            type: string
          required: true
          example: '8.5'
          description:  Voto di riferimento per ottenere il conteggio degli studenti con votazione maggiore del sudetto parametro. I decimali vanno separati col punto.
        - name: Vecchio_Ordinamento
          in: query
          schema:
            type: boolean
            enum: [false, true]
          required: true
          description:  false = nuovo ordinamento, true = vecchio ordinamento
      responses:
        '200':
          description: Viene restituito il conteggio degli studenti con votazione maggiore del parametro Voto
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /corsierogati:
    get:
      tags:
        - corsierogati
      operationId: corsierogati
      summary: Elenco dei corsi erogati da un IFS
      description: Elenco dei corsi erogati da un IFS
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito l'elenco dei corsi erogati da un IFS
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /studentedettaglioiscrizione:
    get:
      tags:
        - studentedettaglioiscrizione
      operationId: studentedettaglioiscrizione
      summary: Studente iscritto con dettaglio iscrizione
      description: Studente iscritto con dettaglio iscrizione
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: codice_fiscale
          in: query
          schema:
            type: string
          required: true
          description: Codice fiscale dello studente per cui è fatta la richiesta dati
      responses:
        '200':
          description: Viene restituito il dettaglio iscrizione per lo studente indicato mediante il parametro codice fiscale (CF)
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /studenteelencotitoli:
    get:
      tags:
        - studenteelencotitoli
      operationId: studenteelencotitoli
      summary: Elenco dei titoli conseguiti per lo studente iscritto
      description: Elenco dei titoli conseguiti per lo studente iscritto
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: codice_fiscale
          in: query
          schema:
            type: string
          required: true
          description: Codice fiscale dello studente per cui è fatta la richiesta dati
      responses:
        '200':
          description: Viene restituito l'elenco dei titoli conseguiti per lo studente iscritto indicato mediante il parametro codice fiscale (CF)
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /studenticontitolo:
    get:
      tags:
        - studenticontitolo
      operationId: studenticontitolo
      summary: Elenco degli studenti che hanno conseguito almeno un titolo
      description: Elenco degli studenti che hanno conseguito almeno un titolo
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito l'elenco degli studenti che hanno conseguito almeno un titolo
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /studentiiscritti:
    get:
      tags:
        - studentiiscritti
      operationId: studentiiscritti
      summary: Elenco studenti iscritti presso quell'IFS
      description: Elenco studenti iscritti presso quell'IFS
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito l'elenco studenti iscritti presso quell'IFS
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /provadiploma:
    get:
      tags:
        - provadiploma
      operationId: provadiploma
      summary: Prova del diploma di istruzione terziaria/certificato/laurea supplement – Diploma supplement o Diploma di istruzione terziaria
      description: Prova del diploma di istruzione terziaria/certificato/laurea supplement – Diploma supplement o Diploma di istruzione terziaria
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: codice_fiscale
          in: query
          schema:
            type: string
          required: true
          description: Codice fiscale dello studente per cui è fatta la richiesta dati
      responses:
        '200':
          description: Viene restituita la prova del diploma di istruzione terziaria/certificato/laurea supplement – Diploma supplement o Diploma di istruzione terziaria
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
