#
# Questo e' solo un esempio in formato OpenAPI 3.0.1 delle implementazioni API REST che metterà a disposizione ISIDATA 
#
openapi: 3.0.1
info:
  title: API ISIUniv23
  description: ISIDATA - API Tracciati record
  version: '0.1'
components:  
  securitySchemes:
    testAutenticazione:
        type: http
        scheme: basic
security:  
    - testAutenticazione: []
servers:
   - url: https://servizi1.isidata.net
paths:
  /ISIUniv23/api/SituazioneStudente:
    get:
      operationId: Conteggio_Iscritti_Corso_PerAnno
      summary: Numero di studenti iscritti a quel Corso di Studi raggruppati per anno di corso
      description: Situazione studente con codice fiscale in tempo reale inclusa di esami sostenuti
      parameters:
        - name: CUStudente
          in: query
          example: 123456
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Lo studente è stato trovato e viene restituita formato json la sua situazione in tempo reale inclusa di esami sostenuti
          content:
            application/json:
              schema:
                type: object
        '400':
          description: I paramentri CUStudente e CUAteneo sono obbligatori
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/CorsiErogati:
    get:
      operationId: getCorsiErogati
      summary: Elenco corsi erogati in tempo reale
      description: Elenco corsi erogati con statistiche numero iscritti per anno di corso in tempo reale
      parameters:
        - name: AnnoAccademico
          in: query
          example: 2023/2024
          schema:
            type: string
          required: true
          description: Anno Accademico di riferimento per l'elaborazione della statistica
      responses:
        '200':
          description: viene restituito formato json l'elenco corsi erogati con statistiche numero iscritti per anno di corso in tempo reale
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro AnnoAccademico obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
