#
# Formato OpenAPI 3.0.1 delle implementazioni API REST che mette a disposizione ISIDATA. L'autenticazione sarà basata su token, ma per adesso essendo visibili dati fittizi, è sufficiente passare nell'header la chiave Authorization col valore basic test:test
#
openapi: 3.0.1
info:
  title: API ISIUniv23
  description: ISIDATA - API Tracciati record
  version: '0.1'
components:  
  securitySchemes:
    testAutenticazione:
        type: http
        scheme: basic
security:  
    - testAutenticazione: []
servers:
   - url: https://servizi1.isidata.net
paths:
  /ISIUniv23/api/Conteggio_Iscritti_Corso_PerAnno:
    get:
      operationId: Conteggio_Iscritti_Corso_PerAnno
      summary: Numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
      description: Numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito il numero di studenti iscritti ai Corsi di Studio raggruppati per anno di corso
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Conteggio_Iscritti_Corsi:
    get:
      operationId: Conteggio_Iscritti_Corsi
      summary: Numero di studenti iscritti ai Corsi di Studio
      description: Numero di studenti iscritti ai Corsi di Studio
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito il numero di studenti iscritti ai Corsi di Studio
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Conteggio_Studenti_Votazione_MaggioreDi:
    get:
      operationId: Conteggio_Studenti_Votazione_MaggioreDi
      summary: Numero di studenti che hanno conseguito il titolo con votazione maggiore di X (parametro Voto)
      description: Numero di studenti che hanno conseguito il titolo con votazione maggiore di X (parametro Voto)
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: Voto
          in: query
          schema:
            type: string
          required: true
          example: 8.5
          description:  Voto di riferimento per ottenere il conteggio degli studenti con votazione maggiore del sudetto parametro. I decimali vanno separati col punto.
        - name: Vecchio_Ordinamento
          in: query
          schema:
            type: integer
            enum: [0, 1]
          required: true
          description:  0 = nuovo ordinamento, 1 = vecchio ordinamento
      responses:
        '200':
          description: Viene restituito il conteggio degli studenti con votazione maggiore del parametro Voto
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Corsi_Erogati:
    get:
      operationId: Corsi_Erogati
      summary: Elenco dei corsi erogati da un IFS
      description: Elenco dei corsi erogati da un IFS
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito l'elenco dei corsi erogati da un IFS
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Studente_Dettaglio_Iscrizione:
    get:
      operationId: Studente_Dettaglio_Iscrizione
      summary: Studente iscritto con dettaglio iscrizione
      description: Studente iscritto con dettaglio iscrizione
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: CF
          in: query
          schema:
            type: string
          required: true
          description: Codice fiscale dello studente per cui è fatta la richiesta dati
      responses:
        '200':
          description: Viene restituito il dettaglio iscrizione per lo studente indicato mediante il parametro codice fiscale (CF)
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Studente_Elenco_Titoli:
    get:
      operationId: Studente_Elenco_Titoli
      summary: Elenco dei titoli conseguiti per lo studente iscritto
      description: Elenco dei titoli conseguiti per lo studente iscritto
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: CF
          in: query
          schema:
            type: string
          required: true
          description: Codice fiscale dello studente per cui è fatta la richiesta dati
      responses:
        '200':
          description: Viene restituito l'elenco dei titoli conseguiti per lo studente iscritto indicato mediante il parametro codice fiscale (CF)
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Studenti_Con_Titolo:
    get:
      operationId: Studenti_Con_Titolo
      summary: Elenco degli studenti che hanno conseguito almeno un titolo
      description: Elenco degli studenti che hanno conseguito almeno un titolo
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito l'elenco degli studenti che hanno conseguito almeno un titolo
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Studenti_Iscritti:
    get:
      operationId: Studenti_Iscritti
      summary: Elenco studenti iscritti presso quell'IFS
      description: Elenco studenti iscritti presso quell'IFS
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
      responses:
        '200':
          description: Viene restituito l'elenco studenti iscritti presso quell'IFS
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
  /ISIUniv23/api/Prova_Diploma:
    get:
      operationId: Prova_Diploma
      summary: Prova del diploma di istruzione terziaria/certificato/laurea supplement – Diploma supplement o Diploma di istruzione terziaria
      description: Prova del diploma di istruzione terziaria/certificato/laurea supplement – Diploma supplement o Diploma di istruzione terziaria
      parameters:
        - name: CodiceIPA
          in: query
          schema:
            type: string
          required: true
          description:  Indice delle Pubbliche Amministrazioni, riferimento univoco dell'IFS
        - name: CF
          in: query
          schema:
            type: string
          required: true
          description: Codice fiscale dello studente per cui è fatta la richiesta dati
      responses:
        '200':
          description: Viene restituita la prova del diploma di istruzione terziaria/certificato/laurea supplement – Diploma supplement o Diploma di istruzione terziaria
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Parametro CodiceIPA obbligatorio
        '401':
          description: Informazioni sull'autorizzazione mancanti o non valide
